handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 1
    max-connections: 1
    threads:
      max: 2
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 10
